// Auto-generated by make — do not edit
let buildVersion = "1.5.3"
let buildCommit = "caa78d8"
let buildBranch = "main"
let buildDate = "2026-06-09 22:09:15 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
